# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crm.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\tcrm.proto\x12\tcrm_proto"R\n\x12\x43ontactInfoRequest\x12\x12\n\ncontact_id\x18\x01 \x01(\t\x12\x12\n\ndepartment\x18\x02 \x01(\t\x12\x14\n\x0corganisation\x18\x03 \x01(\t"\xf8\x01\n\x13\x43ontactInfoResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\n\n\x02id\x18\x02 \x01(\t\x12\x12\n\ndepartment\x18\x03 \x01(\t\x12\x14\n\x0corganisation\x18\x04 \x01(\t\x12\x12\n\nfirst_name\x18\x05 \x01(\t\x12\x11\n\tlast_name\x18\x06 \x01(\t\x12\r\n\x05\x65mail\x18\x07 \x01(\t\x12\x14\n\x0cphone_number\x18\x08 \x01(\t\x12\r\n\x05title\x18\t \x01(\t\x12\r\n\x05owner\x18\n \x01(\t\x12\x13\n\x0b\x64\x65signation\x18\x0b \x01(\t\x12\x0c\n\x04tags\x18\x0c \x01(\t\x12\x0f\n\x07\x63ompany\x18\r \x01(\t2\\\n\x0b\x43ontactData\x12M\n\nGetContact\x12\x1d.crm_proto.ContactInfoRequest\x1a\x1e.crm_proto.ContactInfoResponse"\x00\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "crm_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _CONTACTINFOREQUEST._serialized_start = 24
    _CONTACTINFOREQUEST._serialized_end = 106
    _CONTACTINFORESPONSE._serialized_start = 109
    _CONTACTINFORESPONSE._serialized_end = 357
    _CONTACTDATA._serialized_start = 359
    _CONTACTDATA._serialized_end = 451
# @@protoc_insertion_point(module_scope)
