# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from common.grpc.protopys import crm_pb2 as crm__pb2


class ContactDataStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetContact = channel.unary_unary(
            "/crm_proto.ContactData/GetContact",
            request_serializer=crm__pb2.ContactInfoRequest.SerializeToString,
            response_deserializer=crm__pb2.ContactInfoResponse.FromString,
        )


class ContactDataServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ContactDataServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetContact": grpc.unary_unary_rpc_method_handler(
            servicer.GetContact,
            request_deserializer=crm__pb2.ContactInfoRequest.FromString,
            response_serializer=crm__pb2.ContactInfoResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "crm_proto.ContactData", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class ContactData(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetContact(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/crm_proto.ContactData/GetContact",
            crm__pb2.ContactInfoRequest.SerializeToString,
            crm__pb2.ContactInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
