# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from common.grpc.protopys import price_settings_pb2 as price__settings__pb2


class PriceSettingsDataStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPriceSettings = channel.unary_unary(
            "/price_settings.proto.PriceSettingsData/GetPriceSettings",
            request_serializer=price__settings__pb2.PriceSettingsInfoRequest.SerializeToString,
            response_deserializer=price__settings__pb2.PriceSettingsInfoResponse.FromString,
        )


class PriceSettingsDataServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPriceSettings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_PriceSettingsDataServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetPriceSettings": grpc.unary_unary_rpc_method_handler(
            servicer.GetPriceSettings,
            request_deserializer=price__settings__pb2.PriceSettingsInfoRequest.FromString,
            response_serializer=price__settings__pb2.PriceSettingsInfoResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "price_settings.proto.PriceSettingsData", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class PriceSettingsData(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPriceSettings(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/price_settings.proto.PriceSettingsData/GetPriceSettings",
            price__settings__pb2.PriceSettingsInfoRequest.SerializeToString,
            price__settings__pb2.PriceSettingsInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
