# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: price_settings.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x14price_settings.proto\x12\x14price_settings.proto"0\n\x18PriceSettingsInfoRequest\x12\x14\n\x0corganisation\x18\x01 \x01(\t"\xac\x01\n\x19PriceSettingsInfoResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\n\n\x02id\x18\x02 \x01(\t\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t\x12\x1d\n\x15price_symbol_position\x18\x04 \x01(\t\x12\x17\n\x0fprice_seperator\x18\x05 \x01(\t\x12\x16\n\x0eno_of_decimals\x18\x06 \x01(\x03\x12\x12\n\ncod_status\x18\x07 \x01(\x08\x32\x8a\x01\n\x11PriceSettingsData\x12u\n\x10GetPriceSettings\x12..price_settings.proto.PriceSettingsInfoRequest\x1a/.price_settings.proto.PriceSettingsInfoResponse"\x00\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "price_settings_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _PRICESETTINGSINFOREQUEST._serialized_start = 46
    _PRICESETTINGSINFOREQUEST._serialized_end = 94
    _PRICESETTINGSINFORESPONSE._serialized_start = 97
    _PRICESETTINGSINFORESPONSE._serialized_end = 269
    _PRICESETTINGSDATA._serialized_start = 272
    _PRICESETTINGSDATA._serialized_end = 410
# @@protoc_insertion_point(module_scope)
