# Generated by Django 4.1.5 on 2023-05-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisations",
            name="api_key",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="organisations",
            name="terms_conditions",
            field=models.BooleanField(default=False),
        ),
    ]
